### ISSUE TITLE
Trouble signing with `%20` character in url for 

### ISSUE THREAD

**Issue by adamn** [imgix/imgix-python#21]
When signing a url with a `+` encoded as `%20` for a web proxy secure source, the signing fails.

Try encoding:
`http://www.brookings.edu/~/media/research/images/l/lk%20lo/london_bigben_flags001/london_bigben_flags001_16x9.jpg`

```python
>>> import imgix
>>> image_url_builder = imgix.UrlBuilder(IMGIX_URL, sign_key=IMGIX_SIGN_KEY, use_https=True)
>>> image_url = 'http://www.brookings.edu/~/media/research/images/l/lk%20lo/london_bigben_flags001/london_bigben_flags001_16x9.jpg'
>>> options = {'w': 260, 'fit': 'crop', 'crop': 'entropy'}
>>> image_url_builder.create_url(image_url, options)
'https://factr-url.imgix.net/http%3A%2F%2Fwww.brookings.edu%2F%7E%2Fmedia%2Fresearch%2Fimages%2Fl%2Flk%2520lo%2Flondon_bigben_flags001%2Flondon_bigben_flags001_16x9.jpg?crop=entropy&fit=crop&ixlib=python-1.1.0&w=260&s=473639e97d47f1b991e46ba670042358'
```

The signed url throws a 401.

**Comment by paulstraw** [comment]
Hey there @adamn. The library is designed to accept unencoded URLs. If you pass in an unencoded URL, this should work as expected. Please let me know if you're still running into issues!

**Comment by adamn** [comment]
`http://www.brookings.edu/~/media/research/images/l/lk%20lo/london_bigben_flags001/london_bigben_flags001_16x9.jpg` is the url I have.  If I convert the `%20` to a `+` then the signature will work but the underlying url will not exist.  If I don't convert it, the url does not get signed correctly and the Imgix server returns a 401.  Is there any solution?

**Comment by paulstraw** [comment]
Yes. The issue here isn't the space character itself, but that part of the URL being passed has been encoded, while part hasn't (the `/`, `~`, and other characters). To make this a bit more straightforward, I've just published version 1.1.1, which automatically unescapes passed URLs before re-escaping them. Let me know if you have any more questions!

**Comment by adamn** [comment]
Cheers!

**Comment by adamn** [comment]
Sorry, this still doesn't work for me.  I still get a 'bad request' on the imgix server because of the bad signature.  Also, it looks like your test asserts the url, not the signature (which is the problem since I'm getting a 401 - i.e. the signature isn't correct).

**Comment by paulstraw** [comment]
Hey @adamn, can you send through the new URL that's being generated?

**Comment by adamn** [comment]
It's in the initial part of the ticket.  Sorry don't have it with me right now.

**Comment by paulstraw** [comment]
Hmm, you shouldn't be getting the same output with the `1.1.1` version of the library. When you're able, could you let me know what the new URL you're getting is? I can generate it on my end, but just want to make sure there's not anything else going on here.

**Comment by adamn** [comment]
These are the steps for 1.1.1.  The final url returns a 400 now.  Just to note, I used to get a 401 with 1.1.0

```
>>> import imgix
>>> imgix._version.__version__
'1.1.1'
>>> image_url_builder = imgix.UrlBuilder(IMGIX_URL, sign_key=IMGIX_SIGN_KEY, use_https=True)
>>> image_url = 'http://www.brookings.edu/~/media/research/images/l/lk%20lo/london_bigben_flags001/london_bigben_flags001_16x9.jpg'
>>> options = {'w': 260, 'fit': 'crop', 'crop': 'entropy'}
>>> image_url_builder.create_url(image_url, options)
'https://factr-url.imgix.net/http%3A%2F%2Fwww.brookings.edu%2F%7E%2Fmedia%2Fresearch%2Fimages%2Fl%2Flk%20lo%2Flondon_bigben_flags001%2Flondon_bigben_flags001_16x9.jpg?crop=entropy&fit=crop&ixlib=python-1.1.1&w=260&s=c09df394cd0c270f82afaa57c29bab47'
```

**Comment by paulstraw** [comment]
Okay, after a bit more digging on this, I've realized that the encoded space character was a red herring. The encoding of the space was actually correct before. What's messing things up is the lack of The encoding that was _actually_ messed up was the `~`. (Working URL: `https://factr-url.imgix.net/http%3A%2F%2Fwww.brookings.edu%2F~%2Fmedia%2Fresearch%2Fimages%2Fl%2Flk%2520lo%2Flondon_bigben_flags001%2Flondon_bigben_flags001_16x9.jpg?crop=entropy&fit=crop&ixlib=python-1.1.1&w=260&s=02e201bd94fc0241051f540e6149699d`)

I'm getting this all patched up, and will have a 1.1.2 out shortly.

**Comment by paulstraw** [comment]
Alrighty @adamn, I just bumped this and verified with your example URL. Should be good to go!
